name = "content-server"
compatibility_date = "2024-12-28"
compatibility_flags = [ "nodejs_compat", "nodejs_compat_populate_process_env" ]
routes = [
  { pattern = "content.trpfrog.net", custom_domain = true }
]

[assets]
directory = "./dist"
binding = "ASSETS"
